import type { UserStory } from "./story-schema";

/**
 * Platform-agnostic backlog provider seam.
 *
 * The product-owner subagent produces a `UserStory` (see ./story-schema). That
 * story is serialised to a `CanonicalPayload` that contains NO provider-specific
 * fields — no GitHub issue numbers, no Jira keys, no Azure DevOps IDs. Each
 * concrete provider (GitHub, Azure DevOps, Jira, ...) is responsible for mapping
 * the canonical payload onto its own API. R1 ships only the GitHub provider;
 * the console provider is a safe default that never performs a network call and
 * is used for dry runs / local development.
 */
export interface CanonicalPayload {
  story: UserStory;
  acceptanceCriteria: { given: string; when: string; then: string }[];
  examples: { input: string; output: string }[];
  constraints: string[];
  nfrs: { performance: string; security: string; latency: string };
  openQuestions: string[];
  /** The GitHub issue that triggered generation; stamped onto the new story issue. */
  sourceIssueNumber?: number;
}

export function toCanonicalPayload(story: UserStory): CanonicalPayload {
  return {
    story,
    acceptanceCriteria: story.acceptanceCriteria,
    examples: story.examples,
    constraints: story.constraints,
    nfrs: story.nfrs,
    openQuestions: story.openQuestions,
  };
}

export interface PublishResult {
  delivered: boolean;
  mode: "dry-run" | "live";
  providerId: string;
  url?: string;
  error?: string;
}

export interface BacklogProvider {
  id: string;
  publish(payload: CanonicalPayload): Promise<PublishResult>;
}

const GITHUB_PROVIDER_ID = "github";

function githubConfiguredToken(): string | undefined {
  return (
    process.env.GH_STORY_TOKEN ||
    process.env.GH_RELEASE_TOKEN ||
    process.env.GITHUB_TOKEN
  );
}

/**
 * The GitHub provider creates a new *story* issue linked back to the source
 * issue via `sourceIssueNumber`. It is registered but NOT the default — the
 * default remains `console` (dry run) so nothing is created until the operator
 * opts in. Requires `issues: write` scope on the token; a 403 is reported with
 * an explicit scope message rather than swallowed.
 */
class GitHubProvider implements BacklogProvider {
  id = GITHUB_PROVIDER_ID;

  async publish(payload: CanonicalPayload): Promise<PublishResult> {
    const token = githubConfiguredToken();
    if (!token) {
      return {
        delivered: false,
        mode: "dry-run",
        providerId: this.id,
        error:
          "No GitHub token configured (set GH_STORY_TOKEN / GH_RELEASE_TOKEN / GITHUB_TOKEN). " +
          "Refusing to create a story issue.",
      };
    }

    const owner = process.env.GITHUB_REPO_OWNER || "ricardoblackskye";
    const repo = process.env.GITHUB_REPO_NAME || "agent-eve";
    const story = payload.story;

    const issueBody = [
      `> Generated by the Product Owner subagent from #${payload.sourceIssueNumber ?? "???"}`,
      "",
      `**Intent**`,
      story.intent,
      "",
      `**Acceptance Criteria**`,
      ...story.acceptanceCriteria.map(
        (c) => `- given ${c.given}, when ${c.when}, then ${c.then}`,
      ),
      "",
      `**Examples**`,
      ...story.examples.map((e) => `- \`${e.input}\` → \`${e.output}\``),
      "",
      `**Constraints**`,
      ...story.constraints.map((c) => `- ${c}`),
      "",
      `**NFRs**`,
      `- performance: ${story.nfrs.performance}`,
      `- security: ${story.nfrs.security}`,
      `- latency: ${story.nfrs.latency}`,
    ].join("\n");

    try {
      const res = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/issues`,
        {
          method: "POST",
          headers: {
            authorization: `Bearer ${token}`,
            accept: "application/vnd.github+json",
            "content-type": "application/json",
            "x-github-api-version": "2022-11-28",
          },
          body: JSON.stringify({
            title: `[Story] ${story.title}`,
            body: issueBody,
          }),
        },
      );

      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        if (res.status === 403) {
          return {
            delivered: false,
            mode: "dry-run",
            providerId: this.id,
            error:
              `GitHub API 403: the token lacks 'issues: write'. ` +
              `Details: ${err?.message || res.statusText}`,
          };
        }
        return {
          delivered: false,
          mode: "dry-run",
          providerId: this.id,
          error: `GitHub API ${res.status}: ${err?.message || res.statusText}`,
        };
      }

      const data = (await res.json()) as { html_url: string; number: number };
      return {
        delivered: true,
        mode: "live",
        providerId: this.id,
        url: data.html_url,
      };
    } catch (err) {
      return {
        delivered: false,
        mode: "dry-run",
        providerId: this.id,
        error: `Failed to create story issue: ${err instanceof Error ? err.message : String(err)}`,
      };
    }
  }
}

class ConsoleProvider implements BacklogProvider {
  id = "console";
  async publish(payload: CanonicalPayload): Promise<PublishResult> {
    return {
      delivered: false,
      mode: "dry-run",
      providerId: this.id,
    };
  }
}

class UnknownProvider implements BacklogProvider {
  constructor(private readonly requestedId: string) {}
  id = "unknown";
  async publish(_payload: CanonicalPayload): Promise<PublishResult> {
    return {
      delivered: false,
      mode: "dry-run",
      providerId: this.requestedId,
      error: `Provider '${this.requestedId}' is not configured.`,
    };
  }
}

const REGISTRY: Record<string, () => BacklogProvider> = {
  console: () => new ConsoleProvider(),
  [GITHUB_PROVIDER_ID]: () => new GitHubProvider(),
};

/**
 * Cheap runtime check that the configured GitHub token actually carries
 * `issues: write`. The plan flagged this as an *unverified* risk: the token was
 * only ever used for `contents`, so a missing `issues` scope would fail silently
 * at issue-creation time. We probe `/user` + `/rate_limit` and inspect the
 * `X-OAuth-Scopes` header so a missing scope surfaces as an explicit message
 * instead of a confusing 403 on the first create.
 */
export async function checkGitHubTokenScope(): Promise<{
  ok: boolean;
  scopes: string[];
  error?: string;
}> {
  const token = githubConfiguredToken();
  if (!token) {
    return { ok: false, scopes: [], error: "no token configured" };
  }
  try {
    const res = await fetch("https://api.github.com/user", {
      headers: {
        authorization: `Bearer ${token}`,
        accept: "application/vnd.github+json",
      },
    });
    const scopesHeader =
      res.headers.get("x-oauth-scopes") ||
      res.headers.get("X-OAuth-Scopes") ||
      "";
    const scopes = scopesHeader
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
    // `repo` (classic, private+public), `public_repo` (classic, public only),
    // and `issues: write` (fine-grained) all confer issue write access.
    // agent-eve is a public repo, so `public_repo` is sufficient here.
    const hasIssuesWrite = scopes.some((s) =>
      /^(issues: write|repo|public_repo|write:org)$/i.test(s),
    );
    if (!res.ok) {
      return { ok: false, scopes, error: `token rejected (${res.status})` };
    }
    return { ok: hasIssuesWrite, scopes };
  } catch (err) {
    return {
      ok: false,
      scopes: [],
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

/**
 * Resolve a backlog provider by id. Falls back to the console provider (dry
 * run) for unknown ids so callers never have to null-check; an unknown provider
 * reports `delivered: false` rather than throwing.
 */
export function getProvider(id: string): BacklogProvider {
  const factory = REGISTRY[id];
  if (factory) return factory();
  return new UnknownProvider(id);
}
